  $ dune build --display short bin/technologic.bc.js @install lib/x.cma.js lib/x__Y.cmo.js bin/z.cmo.js
        ocamlc lib/stubs$ext_obj
    ocamlmklib lib/dllx_stubs$ext_dll,lib/libx_stubs$ext_lib
      ocamlopt .ppx/js_of_ocaml-ppx/ppx.exe
           ppx lib/.x.objs/x.ml.pp
      ocamldep lib/.x.objs/x.ml.pp.d
        ocamlc lib/.x.objs/x__.{cmi,cmo,cmt}
      ocamlopt lib/.x.objs/x__.{cmx,o}
           ppx lib/.x.objs/y.ml.pp
      ocamldep lib/.x.objs/y.ml.pp.d
        ocamlc lib/.x.objs/x__Y.{cmi,cmo,cmt}
      ocamlopt lib/.x.objs/x__Y.{cmx,o}
           ppx bin/.technologic.eobjs/technologic.ml.pp
      ocamldep bin/.technologic.eobjs/technologic.ml.pp.d
           ppx bin/.technologic.eobjs/z.ml.pp
      ocamldep bin/.technologic.eobjs/z.ml.pp.d
   js_of_ocaml .js/js_of_ocaml/js_of_ocaml.cma.js
   js_of_ocaml lib/.x.objs/x__Y.cmo.js
        ocamlc lib/.x.objs/x.{cmi,cmo,cmt}
      ocamlopt lib/.x.objs/x.{cmx,o}
      ocamlopt lib/x.{a,cmxa}
      ocamlopt lib/x.cmxs
   js_of_ocaml .js/stdlib/stdlib.cma.js
   js_of_ocaml bin/technologic.bc.runtime.js
        ocamlc lib/x.cma
   js_of_ocaml lib/x.cma.js
        ocamlc bin/.technologic.eobjs/z.{cmi,cmo,cmt}
   js_of_ocaml bin/.technologic.eobjs/z.cmo.js
        ocamlc bin/.technologic.eobjs/technologic.{cmi,cmo,cmt}
   js_of_ocaml bin/.technologic.eobjs/technologic.cmo.js
     jsoo_link bin/technologic.bc.js
  $ $NODE ./_build/default/bin/technologic.bc.js
  buy it
  use it
  break it
  fix it
  $ dune build --display short bin/technologic.bc.js @install --profile release
        ocamlc lib/.x.objs/x__.{cmi,cmo,cmt}
        ocamlc lib/.x.objs/x__Y.{cmi,cmo,cmt}
        ocamlc lib/.x.objs/x.{cmi,cmo,cmt}
        ocamlc lib/x.cma
      ocamlopt lib/.x.objs/x__.{cmx,o}
      ocamlopt lib/.x.objs/x__Y.{cmx,o}
      ocamlopt lib/.x.objs/x.{cmx,o}
      ocamlopt lib/x.{a,cmxa}
      ocamlopt lib/x.cmxs
        ocamlc bin/.technologic.eobjs/z.{cmi,cmo,cmt}
        ocamlc bin/.technologic.eobjs/technologic.{cmi,cmo,cmt}
        ocamlc bin/technologic.bc
   js_of_ocaml bin/technologic.bc.js
  $ $NODE ./_build/default/bin/technologic.bc.js
  buy it
  use it
  break it
  fix it
