(executable
 (name example)
 (flags (:standard -w -9-27))
 (ctypes
  (external_library_name examplelib)
  (deps (source_tree vendor))
  (build_flags_resolver
   (vendored
    (c_flags "-Ivendor")
    (c_library_flags ("-Lvendor" "-lexample"))))
  (headers (include (:include includes.sexp)))
  (type_description
   (instance Types)
   (functor Type_description))
  (function_description
   (instance Functions)
   (functor Function_description))
  (generated_entry_point C)))

(rule
 (action (with-stdout-to includes.sexp (echo "example.h"))))
