# Makefile.config written by configure
OCAML_CORE_STDLIB=/opt/godi/lib/ocaml/std-lib
OCAML_CORE_BIN=/opt/godi/bin
OCAML_CORE_MAN=/opt/godi/man
OCAML_SITELIB=/home/gerd/tmp/fl/site-lib
OCAML_THREADS=posix
OCAMLFIND_BIN=/home/gerd/tmp/fl/bin
OCAMLFIND_MAN=/home/gerd/tmp/fl/man
OCAMLFIND_CONF=/home/gerd/tmp/fl/ocamlfind.conf
OCAML_AUTOLINK=true
EXEC_SUFFIX=
MAKE_TOOLBOX=yes
