#! /bin/sh

set -e

version=`./configure -version 2>/dev/null`
destdir="findlib-$version"
trunk="https://godirepo.camlcity.org/svn/lib-findlib/trunk"
tag="https://godirepo.camlcity.org/svn/lib-findlib/tags/$destdir"

mkdir -p packages
rm -rf "packages/$destdir"
makepkg -spec findlib.files -intree . -outtree "packages/$destdir"
(cd packages; tar czf "$destdir.tar.gz" "$destdir")
echo "Wrote packages/$destdir.tar.gz"

# Checking for svn:

status=$(svn status | grep -v '^\?' || true )

if [ -n "$status" ]; then
    echo "Error: svn status not clean"
    exit 1
else
    printf "Tag revision (y/n)? "
    read answer
    case "$answer" in
        y|Y|yes|YES)
            svn cp "$trunk" "$tag"
            echo "New tag: $tag"
            ;;
        *)
            echo "Nothing tagged."
            ;;
    esac
fi
