#! /bin/sh

set -e

version=`./configure -version 2>/dev/null`
destdir="findlib-$version"

mkdir -p packages
rm -rf "packages/$destdir"
makepkg -spec findlib.files -intree . -outtree "packages/$destdir"
(cd packages; tar czf "$destdir.tar.gz" "$destdir")

echo "Don't forget to update REVISIONS!"
