Test alias module for wrapped libraries:

  $ cat >dune-project <<EOF
  > (lang dune 3.4)
  > EOF

  $ cat >dune <<EOF
  > (library
  >  (name foo))
  > EOF
  $ touch foo.ml bar.ml

  $ dune build
  $ cat _build/default/foo__.ml-gen
  (* generated by dune *)
  
  (** @canonical Foo.Bar *)
  module Bar = Foo__Bar
