Tests for generating opam files with the "available" field.

Feature is only available in 3.11 and later.
  $ cat > dune-project << EOF
  > (lang dune 3.10)
  > (generate_opam_files true)
  > (package
  >  (name foo)
  >  (available (= :os linux)))
  > EOF

  $ dune build @check
  File "dune-project", line 5, characters 1-26:
  5 |  (available (= :os linux)))
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  Error: 'available' is only available since version 3.11 of the dune language.
  Please update your dune-project file to have (lang dune 3.11).
  [1]

  $ cat > dune-project << EOF
  > (lang dune 3.11)
  > (generate_opam_files true)
  > (package
  >  (name foo)
  >  (available (and (<> :os linux) (or (= :arch x86_64) (= :arch arm64)))))
  > EOF

  $ dune build @check

  $ cat foo.opam
  # This file is generated by dune, edit dune-project instead
  opam-version: "2.0"
  depends: [
    "dune" {>= "3.11"}
    "odoc" {with-doc}
  ]
  available: os != "linux" & (arch = "x86_64" | arch = "arm64")
  build: [
    ["dune" "subst"] {dev}
    [
      "dune"
      "build"
      "-p"
      name
      "-j"
      jobs
      "@install"
      "@runtest" {with-test}
      "@doc" {with-doc}
    ]
  ]
