(lang dune 1.10)
(name cohttp)
(version 1.0.0)
(source (github mirage/ocaml-cohttp))
(license ISC)
(authors "Anil Madhavapeddy" "Rudi Grinberg")

(generate_opam_files true)

(package
  (name cohttp)
  (synopsis "An OCaml library for HTTP clients and servers")
  (description "A longer description")
  (depends
    (alcotest :with-test)
    (dune (and :build (> 1.5)))
    (foo (and :dev (> 1.5) (< 2.0)))
    (uri (>= 1.9.0))
    (uri (< 2.0.0))
    (fieldslib (> v0.12))
    (fieldslib (< v0.13))))

(package
  (name cohttp-async)
  (synopsis "HTTP client and server for the Async library")
  (description "A _really_ long description")
  (depends
    (cohttp (>= 1.0.2))
    (conduit-async (>= 1.0.3))
    (async (>= v0.10.0))
    (async (< v0.12))))
