(lang dune 2.0)
(name github)

(generate_opam_files true)

(license MIT)
(maintainers "Anil Madhavapeddy <anil@recoil.org>")
(authors "Anil Madhavapeddy" "David Sheets" "Andy Ray"
  "Jeff Hammerbacher" "Thomas Gazagnaire" "Rudi Grinberg"
  "Qi Li" "Jeremy Yallop" "Dave Tucker")
(source (github mirage/ocaml-github))
(documentation "https://mirage.github.io/ocaml-github/")

(package
 (name github)
 (tags (org:mirage org:xapi-project git))
 (depends
  (ocaml (>= 4.03.0))
  (uri (>= 1.9.0))
  (cohttp (>= 0.99.0))
  (cohttp-lwt (>= 0.99))
  (lwt (>= 2.4.4))
  (atdgen (>= 2.0.0))
  (yojson (>= 1.6.0))
  stringext)
 (synopsis "GitHub APIv3 OCaml library")
 (description "This library provides an OCaml interface to the
[GitHub APIv3](https://developer.github.com/v3/) (JSON).

It is compatible with [MirageOS](https://mirage.io) and also compiles to pure
JavaScript via [js_of_ocaml](http://ocsigen.org/js_of_ocaml)."))

(package
 (name github-jsoo)
 (tags (org:mirage org:xapi-project git))
 (depends
  (ocaml (>= 4.03.0))
  (github (= :version))
  (cohttp (>= 0.99.0))
  (cohttp-lwt-jsoo (>= 0.99.0))
  (js_of_ocaml-lwt (>= 3.4.0)))
 (synopsis "GitHub APIv3 JavaScript library")
 (description "This library provides an OCaml interface to the [GitHub APIv3](https://developer.github.com/v3/)
(JSON). This library installs the JavaScript version, which uses [js_of_ocaml](http://ocsigen.org/js_of_ocaml)."))

(package
 (name github-unix)
 (tags (org:mirage org:xapi-project git))
 (depends
  (ocaml (>= 4.03.0))
  (github (= :version))
  (cohttp (>= 0.99.0))
  (cohttp-lwt-unix (>= 0.99.0))
  stringext
  (lambda-term (>= 2.0))
  (cmdliner (>= 0.9.8))
  base-unix)
 (synopsis "GitHub APIv3 Unix library")
 (description "This library provides an OCaml interface to the [GitHub APIv3](https://developer.github.com/v3/)
(JSON).  This package installs the Unix (Lwt) version."))
