(library
 (name examplelib)
 (flags (:standard -w -9-27))
 (ctypes
  (external_library_name examplelib)
  (deps (source_tree vendor))
  ; LINK_DEPS
  (build_flags_resolver
   (vendored
    ;; hack: multiple -I directives to work around cc commands being run from
    ;; different relative directories.  Is there a cleaner way to do this?
    (c_flags ("-Istubgen/vendor" "-Ivendor"))
    (c_library_flags ("-Lstubgen/vendor" "-lexample"))))
  (headers (include "example.h"))
  (type_description
   (instance Types)
   (functor Type_description))
  (function_description
   (instance Functions)
   (functor Function_description))
  (generated_entry_point C)))
