  $ cat > dune-project << EOF
  > (lang dune 3.10)
  > (package
  >  (name l))
  > EOF

  $ cat > dune << EOF
  > (library
  >  (public_name l))
  > EOF

  $ cat > l.ml << EOF
  > module M = struct
  >   type t = int
  > end
  > EOF

  $ list_json () {
  >   find _build/default/_doc/_json -name '*.html.json' -o -name 'sidebar.json' 2>/dev/null | sort
  > }

  $ list_html () {
  >   find _build/default/_doc/_html -name '*.html' 2>/dev/null | sort
  > }

  $ dune build @doc-json
  $ list_json
  _build/default/_doc/_json/index.html.json
  _build/default/_doc/_json/l/index.html.json
  _build/default/_doc/_json/l/l/L/M/index.html.json
  _build/default/_doc/_json/l/l/L/index.html.json
  _build/default/_doc/_json/l/l/index.html.json

The toplevel index is generated by dune and contains the full odoc JSON output:

  $ cat _build/default/_doc/_json/index.html.json
  {"header":"<h1 id=\"ocaml-package-documentation\"><a href=\"#ocaml-package-documentation\" class=\"anchor\"></a>OCaml package documentation</h1>","type":"documentation","uses_katex":false,"breadcrumbs":[{"name":"","href":null,"kind":"leaf-page"}],"toc":[],"source_anchor":null,"preamble":"<ul><li><a href=\"l/index.html\" title=\"index\">l</a></li></ul>","content":""}

@doc-json does not generate HTML files:

  $ list_html

@doc will continue generating doc as usual (but no JSON):

  $ dune build @doc
  $ list_html
  _build/default/_doc/_html/index.html
  _build/default/_doc/_html/l/index.html
  _build/default/_doc/_html/l/l/L/M/index.html
  _build/default/_doc/_html/l/l/L/index.html
  _build/default/_doc/_html/l/l/index.html
