Test that `dune describe workspace` reports the origin of each module: a
plain source file, a file generated by a `rule` stanza, one generated by
`ocamllex`, one generated by `ocamlyacc`, and the alias module synthesised by
dune itself when wrapping. Exercised for a wrapped library, an unwrapped
library, and an executable.

The dependencies of a `rule`-generated module are opt-in, via
`--with-origin-deps` and `--with-origin-deps-expanded` (see the end of the
test).

  $ cat >dune-project <<EOF
  > (lang dune 3.20)
  > EOF

A wrapped library with all four kinds of source, plus its alias module.

  $ cat >dune <<EOF
  > (library
  >  (name mylib))
  > (ocamllex lexer)
  > (ocamlyacc gram)
  > (rule
  >  (target generated.ml)
  >  (deps (glob_files *.txt))
  >  (action (write-file generated.ml "let x = 0")))
  > EOF

  $ cat >plain.ml <<EOF
  > let x = 0
  > EOF

  $ touch dep.txt extra.txt

  $ cat >lexer.mll <<EOF
  > rule read = parse
  > | eof { () }
  > EOF

  $ cat >gram.mly <<EOF
  > %token EOF
  > %start main
  > %type <unit> main
  > %%
  > main: EOF { () }
  > EOF

A library declared under `(subdir ...)`: the generated origins must point at the
dune file the stanza is actually written in (the parent `dune`), not at the
non-existent `sub/dune`.

  $ mkdir -p sub
  $ cat >>dune <<EOF
  > (subdir sub
  >  (library
  >   (name sublib)))
  > EOF

  $ cat >sub/s.ml <<EOF
  > let x = 0
  > EOF

An unwrapped library: no alias module is synthesised.

  $ mkdir -p unwrapped
  $ cat >unwrapped/dune <<EOF
  > (library
  >  (name mylib_unwrapped)
  >  (wrapped false))
  > (ocamllex ulexer)
  > EOF

  $ cat >unwrapped/u.ml <<EOF
  > let x = 0
  > EOF

  $ cat >unwrapped/ulexer.mll <<EOF
  > rule read = parse
  > | eof { () }
  > EOF

An executable, exercising the separate executables code path.

  $ mkdir -p exe
  $ cat >exe/dune <<EOF
  > (executable
  >  (name main))
  > (ocamllex elexer)
  > (rule
  >  (target egen.ml)
  >  (action (write-file egen.ml "let x = 0")))
  > EOF

  $ cat >exe/main.ml <<EOF
  > let () = ignore Elexer.read; ignore Egen.x
  > EOF

  $ cat >exe/elexer.mll <<EOF
  > rule read = parse
  > | eof { () }
  > EOF

  $ dune describe workspace --lang 0.1 --sanitize-for-tests | censor
  ((root /WORKSPACE_ROOT)
   (build_context _build/default)
   (executables
    ((names (main))
     (requires ())
     (modules
      (((name Main)
        (impl (_build/default/exe/main.ml))
        (intf ())
        (cmt (_build/default/exe/.main.eobjs/byte/dune__exe__Main.cmt))
        (cmti ())
        (origin source))
       ((name Elexer)
        (impl (_build/default/exe/elexer.ml))
        (intf ())
        (cmt (_build/default/exe/.main.eobjs/byte/dune__exe__Elexer.cmt))
        (cmti ())
        (origin
         (ocamllex exe/elexer.mll)))
       ((name Egen)
        (impl (_build/default/exe/egen.ml))
        (intf ())
        (cmt (_build/default/exe/.main.eobjs/byte/dune__exe__Egen.cmt))
        (cmti ())
        (origin
         (dune ((dune_file exe/dune)))))
       ((name Dune__exe)
        (impl (_build/default/exe/.main.eobjs/dune__exe.ml-gen))
        (intf ())
        (cmt (_build/default/exe/.main.eobjs/byte/dune__exe.cmt))
        (cmti ())
        (origin
         (wrapper exe/dune)))))
     (include_dirs (_build/default/exe/.main.eobjs/byte))))
   (library
    ((name mylib)
     (uid $DIGEST1)
     (local true)
     (requires ())
     (source_dir _build/default)
     (modules
      (((name Plain)
        (impl (_build/default/plain.ml))
        (intf ())
        (cmt (_build/default/.mylib.objs/byte/mylib__Plain.cmt))
        (cmti ())
        (origin source))
       ((name Lexer)
        (impl (_build/default/lexer.ml))
        (intf ())
        (cmt (_build/default/.mylib.objs/byte/mylib__Lexer.cmt))
        (cmti ())
        (origin
         (ocamllex lexer.mll)))
       ((name Gram)
        (impl (_build/default/gram.ml))
        (intf (_build/default/gram.mli))
        (cmt (_build/default/.mylib.objs/byte/mylib__Gram.cmt))
        (cmti (_build/default/.mylib.objs/byte/mylib__Gram.cmti))
        (origin
         (ocamlyacc gram.mly)))
       ((name Generated)
        (impl (_build/default/generated.ml))
        (intf ())
        (cmt (_build/default/.mylib.objs/byte/mylib__Generated.cmt))
        (cmti ())
        (origin
         (dune ((dune_file dune)))))
       ((name Mylib)
        (impl (_build/default/mylib.ml-gen))
        (intf ())
        (cmt (_build/default/.mylib.objs/byte/mylib.cmt))
        (cmti ())
        (origin
         (wrapper dune)))))
     (include_dirs (_build/default/.mylib.objs/byte))))
   (library
    ((name mylib_unwrapped)
     (uid $DIGEST2)
     (local true)
     (requires ())
     (source_dir _build/default/unwrapped)
     (modules
      (((name Ulexer)
        (impl (_build/default/unwrapped/ulexer.ml))
        (intf ())
        (cmt (_build/default/unwrapped/.mylib_unwrapped.objs/byte/ulexer.cmt))
        (cmti ())
        (origin
         (ocamllex unwrapped/ulexer.mll)))
       ((name U)
        (impl (_build/default/unwrapped/u.ml))
        (intf ())
        (cmt (_build/default/unwrapped/.mylib_unwrapped.objs/byte/u.cmt))
        (cmti ())
        (origin source))))
     (include_dirs (_build/default/unwrapped/.mylib_unwrapped.objs/byte))))
   (library
    ((name sublib)
     (uid $DIGEST3)
     (local true)
     (requires ())
     (source_dir _build/default/sub)
     (modules
      (((name S)
        (impl (_build/default/sub/s.ml))
        (intf ())
        (cmt (_build/default/sub/.sublib.objs/byte/sublib__S.cmt))
        (cmti ())
        (origin source))
       ((name Sublib)
        (impl (_build/default/sub/sublib.ml-gen))
        (intf ())
        (cmt (_build/default/sub/.sublib.objs/byte/sublib.cmt))
        (cmti ())
        (origin
         (wrapper dune)))))
     (include_dirs (_build/default/sub/.sublib.objs/byte)))))

By default the `dune` origin reports only the generating dune file. The rule's
dependencies are opt-in. Shown here for the glob-dependent `Generated` module.

  $ generated() {
  >   dune describe workspace --lang 0.1 --sanitize-for-tests "$@" \
  >     | censor | sed -n '/(name Generated)/,/(name Mylib)/p' | sed '$d'
  > }

`--with-origin-deps` adds the rule's dependencies as declared (a glob stays a
glob):

  $ generated --with-origin-deps
       ((name Generated)
        (impl (_build/default/generated.ml))
        (intf ())
        (cmt (_build/default/.mylib.objs/byte/mylib__Generated.cmt))
        (cmti ())
        (origin
         (dune
          ((dune_file dune)
           (deps
            ((File_selector
              ((dir (In_build_dir default))
               (predicate (Element (Glob *.txt)))
               (only_generated_files false)))))))))

`--with-origin-deps-expanded` adds them expanded to the concrete matching files:

  $ generated --with-origin-deps-expanded
       ((name Generated)
        (impl (_build/default/generated.ml))
        (intf ())
        (cmt (_build/default/.mylib.objs/byte/mylib__Generated.cmt))
        (cmti ())
        (origin
         (dune
          ((dune_file dune)
           (expanded_deps
            ((In_build_dir default/dep.txt)
             (In_build_dir default/extra.txt)))))))

Both flags together report the dependencies in both forms:

  $ generated --with-origin-deps --with-origin-deps-expanded
       ((name Generated)
        (impl (_build/default/generated.ml))
        (intf ())
        (cmt (_build/default/.mylib.objs/byte/mylib__Generated.cmt))
        (cmti ())
        (origin
         (dune
          ((dune_file dune)
           (deps
            ((File_selector
              ((dir (In_build_dir default))
               (predicate (Element (Glob *.txt)))
               (only_generated_files false)))))
           (expanded_deps
            ((In_build_dir default/dep.txt)
             (In_build_dir default/extra.txt)))))))
