Test `dune describe pkg lock` with autolocking (no committed lock dir).

  $ mkrepo
  $ mkpkg A 1.2.0
  > mkpkg B 2.1+rc1

  $ add_mock_repo_if_needed
  $ enable_pkg

  $ cat > dune-project <<EOF
  > (lang dune 3.20)
  > (package
  >  (name x)
  >  (depends A B))
  > EOF

Before any build there is no lock dir, so describe reports none rather than
failing:
  $ dune describe pkg lock
  No lock directory found for dune.lock (none committed and none generated by a
  build yet).

Trigger autolocking with a build:
  $ dune build @pkg-install 2>&1

After the build, describe reads the internal autolocked lock:
  $ dune describe pkg lock
  Contents of _build/_private/default/.lock/dune.lock:
  - A.1.2.0
  - B.2.1+rc1
