(library
 (name dune_scheduler_tests)
 (modules async_io_tests)
 (inline_tests)
 (preprocess
  (pps ppx_expect))
 (libraries
  stdune
  dune_scheduler
  unix
  threads.posix
  fiber
  ;; This is because of the (implicit_transitive_deps false)
  ;; in dune-project
  ppx_expect.config
  ppx_expect.config_types
  base
  ppx_inline_test.config))

(test
 (name signal_watcher_repro)
 (modules signal_watcher_repro)
 (enabled_if
  (= %{system} macosx))
 (libraries stdune dune_scheduler unix threads.posix fiber))
