(* The implementation of this module is generated by dune when linking
   an executable *)

(* All the placeholders present in the generated module *)
val placeholders : string ref list

type value =
  | Unset
  | Direct of string
  | Placeholder of string ref

val version : value
val statically_linked_libraries : (string * value) list
