(lang dune 2.5)
(name foo)
(version 1.0.0)
(source (github mirage/ocaml-cohttp))
(license ISC)
(authors "Anil Madhavapeddy" "Rudi Grinberg")
(homepage https://my.home.page)

(generate_opam_files true)

(package
 (name foo)
 (version 1.0.1)
 (source (github mirage/foo))
 (license MIT)
 (authors "Foo" "Bar"))
