#! /bin/sh
#
# $Id$
# ----------------------------------------------------------------------
#
# usage: collect_files file ...
#
# Prints the names of the files passed as arguments which actually
# exist and are regular files.

for x in "$@"; do
    if [ -f "$x" ]; then
	echo "$x"
    fi
done

