Basic test showcasing the feature. Every directory creates a new level of aliasing.
  $ dune build
  File "lib/foolib.ml-gen", line 4, characters 10-11:
  4 | module Foo.Bar = Foolib__Bar
                ^
  Error: Syntax error
  [1]

  $ cat _build/default/lib/foolib.ml-gen 
  (* generated by dune *)
  
  (** @canonical Foolib.Foo.Bar *)
  module Foo.Bar = Foolib__Bar
  
  (** @canonical Foolib.Foo.A.B *)
  module Foo.A.B = Foolib__B
  
  module Foolib = struct end
  [@@deprecated "this module is shadowed"]
