(lang dune 1.0)

(using run_test_schemes 0.1)

(run_test_scheme
 (dir_extension tests)
 (extension t)
 (alias testscheme)
 (action (cat %{test})))

(run_test_scheme
 (dir_extension testing)
 (extension t)
 (alias testscheme)
 (action (cat %{test})))
