(library
 (name build_bench_perf)
 (wrapped false)
 (modules perf_counter)
 (libraries stdune))

(executable
 (name bench)
 (modules bench metrics)
 (libraries
  build_bench_perf
  dune_trace
  dune_scheduler
  stdune
  fiber
  dune_lang
  dune_engine
  dune_util
  unix))

(test
 (name perf_counter_tests)
 (modules perf_counter_tests)
 (libraries build_bench_perf stdune))

(rule
 (alias bench)
 (action
  (run ./bench.exe %{bin:dune})))

(executable
 (modules gen_synthetic)
 (libraries unix)
 (name gen_synthetic))

(executable
 (modules gen_synthetic_dune_watch)
 (libraries unix)
 (name gen_synthetic_dune_watch))
