(** This library is a convenience layer on top of raw inotify interface that
    maintains the required client-side bookkeeping to make sense of the events
    generated by the kernel and translate them in a form convenient for the
    client application.

    See [man 7 inotify] for the raw inotify documentation.

    Event processing runs on a background thread. [emit_events] is called from
    that thread and is responsible for transferring events to the scheduler if
    needed.

    Be aware that the interface of inotify makes it easy to write code with race
    conditions or other subtle pitfalls. For instance, stat'ing a file then
    watching it means you have lost any events between the stat and the watch.
    Or the behavior when watching a path whose inode has multiple hardlinks is
    non-obvious. *)

type t

module Event : sig
  type move =
    | Away of string
    | Into of string
    | Move of
        { src : string
        ; dst : string
        }

  type t =
    | Created of string
    | Unlinked of string
    | Modified of string
    | Moved of move
    (** Queue overflow means that you are not consuming events fast enough
        and just lost some of them. This means that some changes to files
        you want might go unnoticed *)
    | Queue_overflow

  val to_string : t -> string
end

type modify_event_selector =
  [ `Any_change
    (** Send a Modified event whenever the contents of the file changes (which
        can be very often when writing a large file) *)
  | `Closed_writable_fd
    (** Only send a Modify event when someone with a file descriptor with write
        permission to that file is closed. There are usually many fewer of these
        events (for large files), but they come later. *)
  ]

(** [create] creates an inotify watcher.

    [emit_events] is called with events emitted by the watcher. *)
val create
  :  modify_event_selector:modify_event_selector
  -> emit_events:(Event.t list -> unit)
  -> t

(** [add t path] add the path to t to be watched. The operation is synchronous,
    so when it returns the kernel has already acknowledged that the watch was
    set up. This may, in fact, block, but it's not safe to run this function in
    a separate thread. *)
val add : t -> string -> unit
