Test alias field on melange.emit stanzas

  $ cat > dune-project <<EOF
  > (lang dune 3.7)
  > (using melange 0.1)
  > EOF

  $ cat > dune <<EOF
  > (melange.emit
  >  (target output)
  >  (alias app))
  > EOF

  $ cat > main.ml <<EOF
  > let () =
  >   print_endline "hello"
  > EOF

  $ dune build @app
  $ node _build/default/output/main.js
  hello

Default alias melange works

  $ cat > dune <<EOF
  > (melange.emit
  >  (target output)
  >  (modules main))
  > (melange.emit
  >  (target output2)
  >  (modules main2))
  > EOF

  $ cat > main2.ml <<EOF
  > let () =
  >   print_endline "hello"
  > EOF

  $ dune clean
  $ dune build @melange
  $ node _build/default/output/main.js
  hello
  $ node _build/default/output2/main2.js
  hello

Using default alias errors out

  $ cat > dune <<EOF
  > (melange.emit
  >  (target output)
  >  (alias melange))
  > EOF

  $ dune clean
  $ dune build @melange
  File "dune", line 3, characters 1-16:
  3 |  (alias melange))
       ^^^^^^^^^^^^^^^
  Error: The alias "melange" is assigned implicitly by Dune to include all
  dependencies generated by all melange.emit stanzas found in the project. To
  use an alias for this particular stanza, use a different name.
  [1]
