Test compile_flags are passed to JS file emission

  $ cat > dune-project <<EOF
  > (lang dune 3.13)
  > (using melange 0.1)
  > EOF

  $ cat > main.ml <<EOF
  > let () = Js.log "hello"
  > EOF

  $ cat > dune <<EOF
  > (melange.emit
  >  (target output)
  >  (emit_stdlib false)
  >  (modules main)
  >  (compile_flags :standard --mel-no-version-header))
  > EOF

  $ dune build @melange

File is generated with the "Generated by Melange" header even though we
specified the opposite in flags

  $ cat _build/default/output/main.js
  'use strict';
  
  
  console.log("hello");
  /*  Not a pure module */
