(** Core artifact type and operations for odoc.

    An artifact represents a single documentation unit - either a module from a
    library or a page from a package. Artifacts track their source (local file,
    installed file, or generated content) and carry dependency information for
    odoc compilation and linking. *)

open Import

(** The kind of artifact: module documentation or page documentation. *)
type kind =
  | Module : Odoc_target.mod_ * Odoc_target.mod_ Odoc_target.t -> kind
  | Page : Odoc_target.page * Odoc_target.page Odoc_target.t -> kind

(** Where the artifact's source content comes from.

    - [Local_source]: A file in the current workspace
    - [Installed_source]: A file from an installed package
    - [Generated]: Content generated by dune (e.g., index pages) *)
type source =
  | Local_source of Path.Build.t
  | Installed_source of { src_path : Path.t }
  | Generated of
      { content : string
      ; output_path : Path.Build.t
      }

(** An odoc artifact with its metadata and dependencies. *)
type t

(** {1 Accessors} *)

val get_kind : t -> kind
val source_file : t -> Path.t
val generated_content : t -> string option

(** {1 Path computation} *)

(** Path to the compiled .odoc file. *)
val odoc_file : Context.t -> t -> Path.Build.t

(** Path to the linked .odocl file. *)
val odocl_file : Context.t -> t -> Path.Build.t

(** Directory containing .odoc files for this artifact's target. *)
val odoc_dir : Context.t -> t -> Path.Build.t

(** Path to the HTML output file. *)
val html_file : Context.t -> Odoc_paths.Doc_mode.t -> t -> Path.Build.t

(** Path to the JSON output file. *)
val json_file : Context.t -> Odoc_paths.Doc_mode.t -> t -> Path.Build.t

(** Directory target for HTML output (for modules only, None for pages). *)
val html_dir_target : Context.t -> Odoc_paths.Doc_mode.t -> t -> Path.Build.t option

(** Directory target for JSON output (for modules only, None for pages). *)
val json_dir_target : Context.t -> Odoc_paths.Doc_mode.t -> t -> Path.Build.t option

(** {1 Metadata} *)

(** Package this artifact belongs to, if any. *)
val pkg : t -> Package.Name.t option

(** Library name for display/linking purposes. *)
val lib_name : t -> Lib_name.t

(** The library this artifact belongs to, if it's a module artifact. *)
val lib : t -> Lib.t option

(** Extra libraries from odoc-config dependencies. *)
val extra_libs : t -> Lib.t list

(** Extra packages from odoc-config dependencies. *)
val extra_packages : t -> Package.Name.t list

(** Whether this artifact should be hidden from indices (internal modules). *)
val hidden : t -> bool

(** The parent-id for odoc compilation (determines URL structure). *)
val parent_id : t -> string

(** Whether to suppress odoc warnings for this artifact (installed/vendored). *)
val should_suppress_output : t -> bool Memo.t

(** {1 Construction} *)

val create
  :  kind:kind
  -> source:source
  -> extra_libs:Lib.t list
  -> extra_packages:Package.Name.t list
  -> t
