name: Binaries

on:
  workflow_dispatch:

jobs:
  binary:
    name: Create
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-15-intel
            name: x86_64-apple-darwin
            installable: .#
          - os: macos-14
            name: aarch64-apple-darwin
            installable: .#
          - os: ubuntu-22.04
            name: x86_64-unknown-linux-musl
            installable: .#dune-static
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # for git describe
      - uses: cachix/install-nix-action@v31
      - run: echo "(version $(git describe --always --dirty --abbrev=7))" >> dune-project
      - run: nix build ${{ matrix.installable }}
      - uses: actions/upload-artifact@v5
        with:
          path: result/bin/dune
          name: dune-${{ matrix.name }}
  combine:
    runs-on: ubuntu-latest
    needs: binary
    steps:
      - uses: actions/upload-artifact/merge@v5
        with:
          separate-directories: true
