name: Changelog
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  check-changelog:
    name: Entry Check
    runs-on: ubuntu-slim
    steps:
      - name: Check for a changelog entry
        uses: tarides/changelog-check-action@d58df251c74f4e1ef83bd5194ebf5f383e631321
        with:
          changelog: doc/changes
