Demonstrate that we (wrongly) allow the expected file to be generated by a rule:

  $ make_dune_project 3.18

  $ cat >dune <<EOF
  > (rule (write-file foo.expected "foo bar"))
  > (test
  >  (name foo))
  > EOF

  $ cat >foo.ml <<EOF
  > print_endline "baz";;
  > EOF

  $ dune runtest
  File "foo.expected", line 1, characters 0-0:
  --- foo.expected
  +++ foo.exe.output
  @@ -1 +1 @@
  -foo bar
  \ No newline at end of file
  +baz
  [1]

The promotion wasn't registered

  $ dune promotion list

Therefore, we keep re-running the test

  $ dune runtest
  File "foo.expected", line 1, characters 0-0:
  --- foo.expected
  +++ foo.exe.output
  @@ -1 +1 @@
  -foo bar
  \ No newline at end of file
  +baz
  [1]
